---
# vars file for /home/student/mans/roles/prechecks/
expected_free_mem: 70 # expected to have at least this much free memory on target machine
expected_os_family: Debian # expected to have this as the ansible_os_family
